<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Laporan;
use App\Models\User;

class LaporanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Ambil salah satu user atau admin untuk diasosiasikan dengan laporan
        $user = User::where('role', 'user')->first() ?? User::first();
        $userId = $user ? $user->id : 1;

        $laporans = [
            // INFRASTRUKTUR
            [
                'user_id' => $userId,
                'judul' => 'Jalan berlubang besar di Jalan Raya Bogor',
                'kategori' => 'infrastruktur',
                'deskripsi' => 'Jalan rusak dan berlubang sangat dalam di tengah jalan raya bogor, membahayakan pengendara motor khususnya malam hari.',
                'lokasi' => 'Jalan Raya Bogor KM 24',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Jembatan penghubung retak dan hampir roboh',
                'kategori' => 'infrastruktur',
                'deskripsi' => 'Jembatan beton penghubung antar desa retak parah di bagian penyangga bawah, rawan runtuh jika dilewati kendaraan roda empat.',
                'lokasi' => 'Jembatan Sungai Ciliwung Kelurahan Baru',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Pipa PDAM bocor menggenangi jalan',
                'kategori' => 'infrastruktur',
                'deskripsi' => 'Pipa saluran air bersih bocor besar di pinggir jalan raya sehingga air meluap membanjiri aspal dan merusak permukaan jalan.',
                'lokasi' => 'Pertigaan lampu merah Veteran',
                'status' => 'diproses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Tiang listrik miring hampir roboh ke jalan',
                'kategori' => 'infrastruktur',
                'deskripsi' => 'Ada tiang kabel listrik beton miring ke arah badan jalan setelah ditabrak truk kemarin malam, membahayakan pengendara.',
                'lokasi' => 'Depan Alfamart jalan Perintis Kemerdekaan',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Saluran irigasi warga jebol dan rusak',
                'kategori' => 'infrastruktur',
                'deskripsi' => 'Dinding saluran irigasi pertanian di wilayah kami jebol sepanjang lima meter sehingga air menggenangi persawahan warga.',
                'lokasi' => 'Dusun Sukamaju RT 03',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Aspal jalan mengelupas sepanjang 100 meter',
                'kategori' => 'infrastruktur',
                'deskripsi' => 'Kondisi jalan raya rusak parah, aspal mengelupas dan menyisakan kerikil tajam yang sering membuat pemotor tergelincir.',
                'lokasi' => 'Jalan Hos Cokroaminoto depan PLN',
                'status' => 'selesai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Pagar pembatas jalan tol rusak parah',
                'kategori' => 'infrastruktur',
                'deskripsi' => 'Pagar besi pembatas pengaman di sepanjang pinggir jalan layang rusak dan lepas setelah kecelakaan kemarin.',
                'lokasi' => 'Jalan Layang AP Pettarani KM 4',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // KEBERSIHAN
            [
                'user_id' => $userId,
                'judul' => 'Tumpukan sampah liar menumpuk di pasar',
                'kategori' => 'kebersihan',
                'deskripsi' => 'Banyak warga membuang sampah sembarangan di area belakang pasar sehingga menumpuk tinggi dan menimbulkan bau menyengat.',
                'lokasi' => 'Belakang Pasar Terong',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Limbah industri dibuang ke sungai warga',
                'kategori' => 'kebersihan',
                'deskripsi' => 'Sebuah pabrik membuang sisa limbah cair berwarna hitam pekat langsung ke sungai tanpa diolah, membuat air bau dan ikan mati.',
                'lokasi' => 'Kawasan Industri Sungai Karang',
                'status' => 'diproses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Penebangan pohon pelindung jalan secara liar',
                'kategori' => 'kebersihan',
                'deskripsi' => 'Penebangan liar pohon perindang jalan raya oleh orang tidak dikenal, merusak kelestarian lingkungan dan keindahan kota.',
                'lokasi' => 'Samping Taman Hutan Kota',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Selokan tersumbat sampah plastik memicu banjir',
                'kategori' => 'kebersihan',
                'deskripsi' => 'Saluran air selokan tersumbat penuh sampah plastik dan botol bekas sehingga air mampet dan langsung meluap saat hujan deras.',
                'lokasi' => 'Jalan Toddopuli Raya Timur',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Sampah menumpuk di pinggir sungai',
                'kategori' => 'kebersihan',
                'deskripsi' => 'Tumpukan sampah plastik dan kasur bekas dibuang di bantaran sungai, mencemari air sungai dan mengganggu kebersihan.',
                'lokasi' => 'Pinggir Jembatan Sungai Tallo',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Bangkai binatang di tengah jalan raya',
                'kategori' => 'kebersihan',
                'deskripsi' => 'Ada bangkai anjing mati di tengah jalan utama yang sudah membusuk dan menimbulkan bau busuk mengganggu warga.',
                'lokasi' => 'Jalan Hertasning depan Lapangan',
                'status' => 'selesai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Warga membakar sampah plastik sembarangan',
                'kategori' => 'kebersihan',
                'deskripsi' => 'Pembakaran sampah secara terbuka di pemukiman padat menghasilkan asap hitam tebal yang menyesakkan dada warga sekitar.',
                'lokasi' => 'Kompleks IDI Blok G',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // KETERTIBAN
            [
                'user_id' => $userId,
                'judul' => 'Pedagang kaki lima mengokupasi trotoar jalan',
                'kategori' => 'ketertiban',
                'deskripsi' => 'Banyak lapak PKL berjualan di sepanjang trotoar jalan raya utama sehingga pejalan kaki terpaksa berjalan di badan jalan.',
                'lokasi' => 'Depan stasiun Pasar Minggu',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Aksi balap liar motor di malam hari',
                'kategori' => 'ketertiban',
                'deskripsi' => 'Setiap sabtu malam terjadi balapan liar sepeda motor knalpot bising yang menutup jalan raya dan mengganggu warga tidur.',
                'lokasi' => 'Jalan Boulevard Panakkukang',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Orang gila mengamuk di depan pertokoan',
                'kategori' => 'ketertiban',
                'deskripsi' => 'Ada orang dengan gangguan jiwa mengamuk membawa batu, mengganggu ketertiban umum dan menakuti pengendara serta warga.',
                'lokasi' => 'Depan Ruko Sentra Veteran',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Parkir liar mobil di jalan membuat macet parah',
                'kategori' => 'ketertiban',
                'deskripsi' => 'Parkir liar kendaraan roda empat di sepanjang jalan sempit membuat arus lalu lintas macet total dan menghalangi jalan.',
                'lokasi' => 'Jalan Pengayoman samping Mall',
                'status' => 'diproses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Tawuran antarkelompok remaja bersenjata tajam',
                'kategori' => 'ketertiban',
                'deskripsi' => 'Terjadi aksi tawuran kelompok pemuda saling serang menggunakan senjata tajam di lapangan, meresahkan ketertiban warga.',
                'lokasi' => 'Flyover Urip Sumoharjo',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Pengamen jalanan memaksa meminta uang di lampu merah',
                'kategori' => 'ketertiban',
                'deskripsi' => 'Banyak pengamen liar memaksa dan menggedor kaca mobil meminta uang secara kasar di persimpangan lampu merah.',
                'lokasi' => 'Lampu Merah Flyover',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Pesta minuman keras liar di taman kota',
                'kategori' => 'ketertiban',
                'deskripsi' => 'Sekelompok pemuda sering berkumpul melakukan pesta minuman keras di fasilitas taman kota saat malam hari, mengganggu kenyamanan.',
                'lokasi' => 'Taman Macan Jalan Balai Kota',
                'status' => 'selesai',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // FASILITAS
            [
                'user_id' => $userId,
                'judul' => 'Lampu penerangan jalan umum mati total',
                'kategori' => 'fasilitas',
                'deskripsi' => 'Lampu tiang penerangan jalan mati di sepanjang jalan veteren sehingga kondisi jalan gelap gulita rawan kecelakaan kriminal.',
                'lokasi' => 'Jalan Veteran Selatan kelurahan Mandala',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Kaca halte bus pecah dan dicorat-coret',
                'kategori' => 'fasilitas',
                'deskripsi' => 'Halte bus umum dirusak oleh orang tidak dikenal, kaca penutup pecah berserakan dan tembok halte penuh aksi vandalisme.',
                'lokasi' => 'Halte BRT depan Kantor Gubernur',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Wahana bermain anak di taman kota rusak',
                'kategori' => 'fasilitas',
                'deskripsi' => 'Alat bermain ayunan dan perosotan anak di taman kota kondisinya patah dan berkarat, membahayakan anak-anak.',
                'lokasi' => 'Taman Pakui Sayang',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Toilet umum di taman mati air dan kotor',
                'kategori' => 'fasilitas',
                'deskripsi' => 'Toilet umum tidak bisa digunakan karena kran air mati, bau pesing menyengat, dan kloset tersumbat kotoran.',
                'lokasi' => 'Toilet Taman Karebosi',
                'status' => 'diproses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Kursi halte bus patah tidak bisa diduduki',
                'kategori' => 'fasilitas',
                'deskripsi' => 'Tempat duduk fasilitas umum di halte bus patah besinya sehingga penumpang terpaksa berdiri saat menunggu bus.',
                'lokasi' => 'Halte Bus Depan Unhas',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Fasilitas gym outdoor taman kota patah',
                'kategori' => 'fasilitas',
                'deskripsi' => 'Alat olahraga gym gratis di taman kota kondisinya rusak berkarat dan rantainya lepas sehingga tidak berfungsi.',
                'lokasi' => 'Taman Lapangan Hasanuddin',
                'status' => 'selesai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Papan petunjuk jalan roboh diterjang angin',
                'kategori' => 'fasilitas',
                'deskripsi' => 'Plang rambu arah penunjuk lokasi jalan roboh menghalangi trotoar taman setelah badai hujan kemarin sore.',
                'lokasi' => 'Jalan Jenderal Sudirman samping Monumen',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // LAINNYA
            [
                'user_id' => $userId,
                'judul' => 'Kehilangan dompet berisi dokumen penting KTP',
                'kategori' => 'lainnya',
                'deskripsi' => 'Saya kehilangan dompet hitam berisi KTP, SIM, dan kartu ATM di sekitar pasar tradisional, mohon bantuan informasi.',
                'lokasi' => 'Pasar Baru sub-distrik',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Pelayanan kantor kelurahan sangat lambat',
                'kategori' => 'lainnya',
                'deskripsi' => 'Proses pembuatan kartu keluarga baru di kelurahan memakan waktu terlalu lama dan petugas kurang ramah melayani warga.',
                'lokasi' => 'Kantor Kelurahan Tamamaung',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Apresiasi kinerja petugas kebersihan kelurahan',
                'kategori' => 'lainnya',
                'deskripsi' => 'Terima kasih kepada bapak petugas kebersihan yang sangat sigap membersihkan saluran air kompleks perumahan kami kemarin.',
                'lokasi' => 'Perumahan Graha Indah',
                'status' => 'selesai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Pertanyaan seputar pendaftaran bansos mandiri',
                'kategori' => 'lainnya',
                'deskripsi' => 'Bagaimanakah alur pendaftaran penerima bantuan sosial mandiri untuk warga kurang mampu secara online di kelurahan?',
                'lokasi' => 'RT 04 RW 02',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Kendala pendaftaran aplikasi online daerah',
                'kategori' => 'lainnya',
                'deskripsi' => 'Mengapa aplikasi sistem pendaftaran berkas kependudukan selalu error dan gagal mengunggah dokumen KTP saya?',
                'lokasi' => 'Online Portal',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Informasi jadwal posyandu balita bulan ini',
                'kategori' => 'lainnya',
                'deskripsi' => 'Mohon informasi mengenai tanggal dan tempat pelaksanaan kegiatan posyandu imunisasi untuk bayi di wilayah RT 02.',
                'lokasi' => 'Posyandu Bougenville RT 02',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'judul' => 'Saran penambahan area hijau taman perumahan',
                'kategori' => 'lainnya',
                'deskripsi' => 'Kami menyarankan pihak pengelola menambah tanaman pelindung dan bunga hias di area taman tengah kompleks perumahan.',
                'lokasi' => 'Taman Kompleks Bumi Harapan',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($laporans as $laporan) {
            $laporan['is_training'] = true;
            Laporan::create($laporan);
        }
    }
}
